config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
               confirmations:      'users/confirmations',
               passwords:          'users/passwords',
               registrations:      'users/registrations',
               sessions:           'users/sessions',
               unlocks:            'users/unlocks',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }

  get '/job_change', to: 'players#jobs.html.haml', as: 'jobs'
  post 'players/job_change', to: 'players#job_change', as: 'job_change'

  get '/skills', to: 'players#skills.html.haml', as: 'skills'

  get 'battles/battle'
  get 'battles', to: 'battles#index'
  get '/introduction', to: 'pages#introduction'
  get 'pages/home'
  root to: 'pages#home'
end

app/views/pages/home.html.haml
- bs_c = @bootstrap_class_list
- bs_c.merge!( status_row:   'col-6 mb-3',
               status_col:   '',
               player_name:  'h5 font-weight-bold mr-2',
               job_badge:    'badge badge-light badge-pill h-100',
               job_change_form: 'row',
               job_change_form_select: 'form-control col mr-auto',
               job_change_form_submit: 'btn btn-light col-auto ml-2')

#player-info
  #player_name.mb-4
    %span{ class: bs_c[:player_name] }
      = @player.name
    %span{ class: bs_c[:job_badge] }
      = @current_job.job_name

  #status.row.border.border-secondary.rounded-lg.py-4.mb-5
    #status-lv{ class: bs_c[:status_row] }
      .status-col{ class: bs_c[:status_col] }
        %span{ class: bs_c[:status_badge] } Lv
        = @player.lv
      .status-col{ class: bs_c[:status_col] }
        %span{ class: bs_c[:status_badge] } Job Lv
        = @current_job.job_level

    #status-exp{ class: bs_c[:status_row] }
      .status-col{ class: bs_c[:status_col] }
        %span{ class: bs_c[:status_badge] } Exp
        = @player.exp
      .status-col{ class: bs_c[:status_col] }
        %span{ class: bs_c[:status_badge] } Next Lv
        = @player.next_lv_exp

    #status-params{ class: bs_c[:status_row] }
      .status-col{ class: bs_c[:status_col] }
        %span{ class: bs_c[:status_badge] } HP
        = @player.hp
      .status-col{ class: bs_c[:status_col] }
        %span{ class: bs_c[:status_badge] } Str
        = @player.str
      .status-col{ class: bs_c[:status_col] }
        %span{ class: bs_c[:status_badge] } Vit
        = @player.vit

    #status-etc{ class: bs_c[:status_row] }
      .status-col{ class: bs_c[:status_col] }
        %span{ class: bs_c[:status_badge] } Coin
        = @player.coin

#job-change.mb-5.container
  = form_with url: job_change_path,
              scope: :job_change_list,
              class: bs_c[:job_change_form] do |f|
    = f.hidden_field :current_job_id,
                     value: @player.current_job_id
    = f.select :target_job_id, :post, {}, class: bs_c[:job_change_form_select] do
      - @player.changeable_job_list.each do |job|
        = content_tag :option, job.job_name, value: job.id
    = f.submit 'ジョブチェンジ',
               class: bs_c[:job_change_form_submit]
= link_to jobs_path,
          class: bs_c[:link_btn_block_light] do
  ジョブ

= link_to skills_path,
          class: bs_c[:link_btn_block_light] do
  スキル

= link_to battles_path, class: bs_c[:link_btn_block] do
  %i.fas.fa-dragon
  バトル

app/views/pages/introduction.html.haml
- bs_c = @bootstrap_class_list

%h1{ class: bs_c[:page_title] }
  %i.fas.fa-dragon
  RGA

%section.my-5
  %h2.h5
    RGAとは...
  %section.card.text-dark
    .card-body
      .card-title
        SUPERな放置ゲームです
      .card-text
        %p もしくはタップゲームかも知れません
        %p ご期待ください！

= link_to new_user_registration_path, class: bs_c[:link_list_btn_block] do
  %i.fas.fa-user-plus
  アカウント作成

= link_to new_user_session_path, class: bs_c[:link_list_btn_block] do
  %i.fas.fa-sign-in-alt
  ログイン